// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * An S3-compatible Railway object storage bucket deployed to one environment.
 */
export class Bucket extends pulumi.CustomResource {
    /**
     * Get an existing Bucket resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Bucket {
        return new Bucket(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'railway:index:Bucket';

    /**
     * Returns true if the given object is an instance of Bucket.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Bucket {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Bucket.__pulumiType;
    }

    /**
     * S3 access key ID for the bucket's environment instance.
     */
    declare public /*out*/ readonly accessKeyId: pulumi.Output<string>;
    /**
     * S3 API endpoint, for example https://storage.railway.app.
     */
    declare public /*out*/ readonly endpoint: pulumi.Output<string>;
    /**
     * ID of the environment the bucket is deployed to.
     */
    declare public readonly environmentId: pulumi.Output<string>;
    /**
     * Bucket display name.
     */
    declare public readonly name: pulumi.Output<string | undefined>;
    /**
     * ID of the Railway project that owns the bucket.
     */
    declare public readonly projectId: pulumi.Output<string>;
    /**
     * Immutable Railway bucket ID.
     */
    declare public /*out*/ readonly railwayId: pulumi.Output<string>;
    /**
     * Bucket region.
     */
    declare public readonly region: pulumi.Output<string>;
    /**
     * Globally unique bucket name for the S3 API (display name plus hash).
     */
    declare public /*out*/ readonly s3BucketName: pulumi.Output<string>;
    /**
     * Region value S3 clients should use, for example auto.
     */
    declare public /*out*/ readonly s3Region: pulumi.Output<string>;
    /**
     * S3 secret access key for the bucket's environment instance.
     */
    declare public /*out*/ readonly secretAccessKey: pulumi.Output<string>;
    /**
     * URL style S3 clients should use: virtual or path.
     */
    declare public /*out*/ readonly urlStyle: pulumi.Output<string>;

    /**
     * Create a Bucket resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: BucketArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.environmentId === undefined && !opts.urn) {
                throw new Error("Missing required property 'environmentId'");
            }
            if (args?.projectId === undefined && !opts.urn) {
                throw new Error("Missing required property 'projectId'");
            }
            if (args?.region === undefined && !opts.urn) {
                throw new Error("Missing required property 'region'");
            }
            resourceInputs["environmentId"] = args?.environmentId;
            resourceInputs["name"] = args?.name;
            resourceInputs["projectId"] = args?.projectId;
            resourceInputs["region"] = args?.region;
            resourceInputs["accessKeyId"] = undefined /*out*/;
            resourceInputs["endpoint"] = undefined /*out*/;
            resourceInputs["railwayId"] = undefined /*out*/;
            resourceInputs["s3BucketName"] = undefined /*out*/;
            resourceInputs["s3Region"] = undefined /*out*/;
            resourceInputs["secretAccessKey"] = undefined /*out*/;
            resourceInputs["urlStyle"] = undefined /*out*/;
        } else {
            resourceInputs["accessKeyId"] = undefined /*out*/;
            resourceInputs["endpoint"] = undefined /*out*/;
            resourceInputs["environmentId"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["projectId"] = undefined /*out*/;
            resourceInputs["railwayId"] = undefined /*out*/;
            resourceInputs["region"] = undefined /*out*/;
            resourceInputs["s3BucketName"] = undefined /*out*/;
            resourceInputs["s3Region"] = undefined /*out*/;
            resourceInputs["secretAccessKey"] = undefined /*out*/;
            resourceInputs["urlStyle"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const aliasOpts = { aliases: [{ type: "railway:pkg:Bucket" }] };
        opts = pulumi.mergeOptions(opts, aliasOpts);
        const secretOpts = { additionalSecretOutputs: ["secretAccessKey"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        const replaceOnChanges = { replaceOnChanges: ["environmentId", "projectId", "region"] };
        opts = pulumi.mergeOptions(opts, replaceOnChanges);
        super(Bucket.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Bucket resource.
 */
export interface BucketArgs {
    /**
     * ID of the environment the bucket is deployed to.
     */
    environmentId: pulumi.Input<string>;
    /**
     * Display name for the bucket. Railway generates a name when omitted.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * ID of the Railway project that owns the bucket.
     */
    projectId: pulumi.Input<string>;
    /**
     * Bucket region: sjc (US West), iad (US East), ams (EU West), or sin (Asia Pacific). It cannot change after creation.
     */
    region: pulumi.Input<string>;
}
