// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * A custom domain attached to a Railway service instance.
 */
export class CustomDomain extends pulumi.CustomResource {
    /**
     * Get an existing CustomDomain resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): CustomDomain {
        return new CustomDomain(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'railway:index:CustomDomain';

    /**
     * Returns true if the given object is an instance of CustomDomain.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is CustomDomain {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === CustomDomain.__pulumiType;
    }

    /**
     * Current Railway TLS certificate status.
     */
    declare public /*out*/ readonly certificateStatus: pulumi.Output<string | undefined>;
    /**
     * DNS CNAME value required by Railway.
     */
    declare public /*out*/ readonly cnameTarget: pulumi.Output<string | undefined>;
    /**
     * Custom domain hostname.
     */
    declare public readonly domain: pulumi.Output<string>;
    /**
     * ID of the Railway environment where the domain is attached.
     */
    declare public readonly environmentId: pulumi.Output<string>;
    /**
     * ID of the Railway project that owns the domain.
     */
    declare public readonly projectId: pulumi.Output<string>;
    /**
     * Railway custom domain ID.
     */
    declare public /*out*/ readonly railwayId: pulumi.Output<string>;
    /**
     * ID of the Railway service where the domain is attached.
     */
    declare public readonly serviceId: pulumi.Output<string>;
    /**
     * Optional container port to which Railway routes domain traffic.
     */
    declare public readonly targetPort: pulumi.Output<number | undefined>;
    /**
     * Token used to verify domain ownership.
     */
    declare public /*out*/ readonly verificationToken: pulumi.Output<string | undefined>;

    /**
     * Create a CustomDomain resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: CustomDomainArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.domain === undefined && !opts.urn) {
                throw new Error("Missing required property 'domain'");
            }
            if (args?.environmentId === undefined && !opts.urn) {
                throw new Error("Missing required property 'environmentId'");
            }
            if (args?.projectId === undefined && !opts.urn) {
                throw new Error("Missing required property 'projectId'");
            }
            if (args?.serviceId === undefined && !opts.urn) {
                throw new Error("Missing required property 'serviceId'");
            }
            resourceInputs["domain"] = args?.domain;
            resourceInputs["environmentId"] = args?.environmentId;
            resourceInputs["projectId"] = args?.projectId;
            resourceInputs["serviceId"] = args?.serviceId;
            resourceInputs["targetPort"] = args?.targetPort;
            resourceInputs["certificateStatus"] = undefined /*out*/;
            resourceInputs["cnameTarget"] = undefined /*out*/;
            resourceInputs["railwayId"] = undefined /*out*/;
            resourceInputs["verificationToken"] = undefined /*out*/;
        } else {
            resourceInputs["certificateStatus"] = undefined /*out*/;
            resourceInputs["cnameTarget"] = undefined /*out*/;
            resourceInputs["domain"] = undefined /*out*/;
            resourceInputs["environmentId"] = undefined /*out*/;
            resourceInputs["projectId"] = undefined /*out*/;
            resourceInputs["railwayId"] = undefined /*out*/;
            resourceInputs["serviceId"] = undefined /*out*/;
            resourceInputs["targetPort"] = undefined /*out*/;
            resourceInputs["verificationToken"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const aliasOpts = { aliases: [{ type: "railway:pkg:CustomDomains" }, { type: "railway:pkg:CustomDomain" }] };
        opts = pulumi.mergeOptions(opts, aliasOpts);
        const replaceOnChanges = { replaceOnChanges: ["domain", "environmentId", "projectId", "serviceId"] };
        opts = pulumi.mergeOptions(opts, replaceOnChanges);
        super(CustomDomain.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a CustomDomain resource.
 */
export interface CustomDomainArgs {
    /**
     * Hostname without a scheme, path, or port, for example api.example.com.
     */
    domain: pulumi.Input<string>;
    /**
     * ID of the Railway environment where the domain is attached.
     */
    environmentId: pulumi.Input<string>;
    /**
     * ID of the Railway project that owns the domain.
     */
    projectId: pulumi.Input<string>;
    /**
     * ID of the Railway service where the domain is attached.
     */
    serviceId: pulumi.Input<string>;
    /**
     * Optional container port to which Railway routes domain traffic.
     */
    targetPort?: pulumi.Input<number | undefined>;
}
