// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * A Railway project, the top-level container for services and environments.
 */
export class Project extends pulumi.CustomResource {
    /**
     * Get an existing Project resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Project {
        return new Project(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'railway:index:Project';

    /**
     * Returns true if the given object is an instance of Project.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Project {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Project.__pulumiType;
    }

    /**
     * ID of the project's primary environment, typically production.
     */
    declare public /*out*/ readonly defaultEnvironmentId: pulumi.Output<string>;
    /**
     * Optional project description.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * Name of the project.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Immutable Railway project ID.
     */
    declare public /*out*/ readonly railwayId: pulumi.Output<string>;
    /**
     * Workspace ID that contains the project.
     */
    declare public readonly workspaceId: pulumi.Output<string | undefined>;

    /**
     * Create a Project resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ProjectArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            resourceInputs["description"] = args?.description;
            resourceInputs["name"] = args?.name;
            resourceInputs["workspaceId"] = args?.workspaceId;
            resourceInputs["defaultEnvironmentId"] = undefined /*out*/;
            resourceInputs["railwayId"] = undefined /*out*/;
        } else {
            resourceInputs["defaultEnvironmentId"] = undefined /*out*/;
            resourceInputs["description"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["railwayId"] = undefined /*out*/;
            resourceInputs["workspaceId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const aliasOpts = { aliases: [{ type: "railway:pkg:Project" }] };
        opts = pulumi.mergeOptions(opts, aliasOpts);
        const replaceOnChanges = { replaceOnChanges: ["workspaceId"] };
        opts = pulumi.mergeOptions(opts, replaceOnChanges);
        super(Project.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Project resource.
 */
export interface ProjectArgs {
    /**
     * Optional project description.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Name of the project.
     */
    name: pulumi.Input<string>;
    /**
     * Workspace ID in which to create the project. Projects without one are temporary and expire after 24 hours unless claimed.
     */
    workspaceId?: pulumi.Input<string | undefined>;
}
