// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * A Railway service and its configuration in one environment.
 */
export class Service extends pulumi.CustomResource {
    /**
     * Get an existing Service resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Service {
        return new Service(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'railway:index:Service';

    /**
     * Returns true if the given object is an instance of Service.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Service {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Service.__pulumiType;
    }

    /**
     * GitHub branch deployed by the service.
     */
    declare public readonly branch: pulumi.Output<string | undefined>;
    /**
     * Command Railway runs to build the service.
     */
    declare public readonly buildCommand: pulumi.Output<string | undefined>;
    /**
     * ID of the configured environment.
     */
    declare public readonly environmentId: pulumi.Output<string>;
    /**
     * HTTP path Railway uses for health checks.
     */
    declare public readonly healthcheckPath: pulumi.Output<string | undefined>;
    /**
     * Docker image source.
     */
    declare public readonly image: pulumi.Output<string | undefined>;
    /**
     * Railway service instance ID for the configured environment.
     */
    declare public /*out*/ readonly instanceId: pulumi.Output<string>;
    /**
     * Service name shown in Railway.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Number of service replicas.
     */
    declare public readonly numReplicas: pulumi.Output<number | undefined>;
    /**
     * ID of the Railway project that owns the service.
     */
    declare public readonly projectId: pulumi.Output<string>;
    /**
     * Immutable Railway service ID.
     */
    declare public /*out*/ readonly railwayId: pulumi.Output<string>;
    /**
     * Railway region for the service instance.
     */
    declare public readonly region: pulumi.Output<string | undefined>;
    /**
     * GitHub repository source.
     */
    declare public readonly repo: pulumi.Output<string | undefined>;
    /**
     * Root directory used as the build context.
     */
    declare public readonly rootDirectory: pulumi.Output<string | undefined>;
    /**
     * Command Railway runs to start the service.
     */
    declare public readonly startCommand: pulumi.Output<string | undefined>;

    /**
     * Create a Service resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ServiceArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.environmentId === undefined && !opts.urn) {
                throw new Error("Missing required property 'environmentId'");
            }
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.projectId === undefined && !opts.urn) {
                throw new Error("Missing required property 'projectId'");
            }
            resourceInputs["branch"] = args?.branch;
            resourceInputs["buildCommand"] = args?.buildCommand;
            resourceInputs["environmentId"] = args?.environmentId;
            resourceInputs["healthcheckPath"] = args?.healthcheckPath;
            resourceInputs["image"] = args?.image;
            resourceInputs["name"] = args?.name;
            resourceInputs["numReplicas"] = args?.numReplicas;
            resourceInputs["projectId"] = args?.projectId;
            resourceInputs["region"] = args?.region;
            resourceInputs["repo"] = args?.repo;
            resourceInputs["rootDirectory"] = args?.rootDirectory;
            resourceInputs["startCommand"] = args?.startCommand;
            resourceInputs["instanceId"] = undefined /*out*/;
            resourceInputs["railwayId"] = undefined /*out*/;
        } else {
            resourceInputs["branch"] = undefined /*out*/;
            resourceInputs["buildCommand"] = undefined /*out*/;
            resourceInputs["environmentId"] = undefined /*out*/;
            resourceInputs["healthcheckPath"] = undefined /*out*/;
            resourceInputs["image"] = undefined /*out*/;
            resourceInputs["instanceId"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["numReplicas"] = undefined /*out*/;
            resourceInputs["projectId"] = undefined /*out*/;
            resourceInputs["railwayId"] = undefined /*out*/;
            resourceInputs["region"] = undefined /*out*/;
            resourceInputs["repo"] = undefined /*out*/;
            resourceInputs["rootDirectory"] = undefined /*out*/;
            resourceInputs["startCommand"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const aliasOpts = { aliases: [{ type: "railway:pkg:Service" }] };
        opts = pulumi.mergeOptions(opts, aliasOpts);
        const replaceOnChanges = { replaceOnChanges: ["branch", "environmentId", "image", "projectId", "repo"] };
        opts = pulumi.mergeOptions(opts, replaceOnChanges);
        super(Service.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Service resource.
 */
export interface ServiceArgs {
    /**
     * GitHub branch to deploy. Valid only when repo is set.
     */
    branch?: pulumi.Input<string | undefined>;
    /**
     * Command Railway runs to build the service.
     */
    buildCommand?: pulumi.Input<string | undefined>;
    /**
     * ID of the environment whose service instance is configured.
     */
    environmentId: pulumi.Input<string>;
    /**
     * HTTP path Railway uses for health checks.
     */
    healthcheckPath?: pulumi.Input<string | undefined>;
    /**
     * Docker image source, for example redis:7-alpine. Mutually exclusive with repo.
     */
    image?: pulumi.Input<string | undefined>;
    /**
     * Service name shown in Railway.
     */
    name: pulumi.Input<string>;
    /**
     * Number of service replicas. Must be at least one.
     */
    numReplicas?: pulumi.Input<number | undefined>;
    /**
     * ID of the Railway project that owns the service.
     */
    projectId: pulumi.Input<string>;
    /**
     * Railway region for the service instance.
     */
    region?: pulumi.Input<string | undefined>;
    /**
     * GitHub repository source in owner/repository form. Mutually exclusive with image.
     */
    repo?: pulumi.Input<string | undefined>;
    /**
     * Root directory used as the build context.
     */
    rootDirectory?: pulumi.Input<string | undefined>;
    /**
     * Command Railway runs to start the service.
     */
    startCommand?: pulumi.Input<string | undefined>;
}
