// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * A service-scoped or environment-shared Railway variable.
 */
export class Variable extends pulumi.CustomResource {
    /**
     * Get an existing Variable resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Variable {
        return new Variable(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'railway:index:Variable';

    /**
     * Returns true if the given object is an instance of Variable.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Variable {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Variable.__pulumiType;
    }

    /**
     * ID of the Railway environment that owns the variable.
     */
    declare public readonly environmentId: pulumi.Output<string>;
    /**
     * Variable name.
     */
    declare public readonly key: pulumi.Output<string>;
    /**
     * ID of the Railway project that owns the variable.
     */
    declare public readonly projectId: pulumi.Output<string>;
    /**
     * Composite identifier in projectId/environmentId/serviceId/key form.
     */
    declare public /*out*/ readonly railwayId: pulumi.Output<string>;
    /**
     * Optional service ID, unset for an environment-shared variable.
     */
    declare public readonly serviceId: pulumi.Output<string | undefined>;
    /**
     * Secret variable value.
     */
    declare public readonly value: pulumi.Output<string>;

    /**
     * Create a Variable resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: VariableArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.environmentId === undefined && !opts.urn) {
                throw new Error("Missing required property 'environmentId'");
            }
            if (args?.key === undefined && !opts.urn) {
                throw new Error("Missing required property 'key'");
            }
            if (args?.projectId === undefined && !opts.urn) {
                throw new Error("Missing required property 'projectId'");
            }
            if (args?.value === undefined && !opts.urn) {
                throw new Error("Missing required property 'value'");
            }
            resourceInputs["environmentId"] = args?.environmentId;
            resourceInputs["key"] = args?.key;
            resourceInputs["projectId"] = args?.projectId;
            resourceInputs["serviceId"] = args?.serviceId;
            resourceInputs["value"] = args?.value ? pulumi.secret(args.value) : undefined;
            resourceInputs["railwayId"] = undefined /*out*/;
        } else {
            resourceInputs["environmentId"] = undefined /*out*/;
            resourceInputs["key"] = undefined /*out*/;
            resourceInputs["projectId"] = undefined /*out*/;
            resourceInputs["railwayId"] = undefined /*out*/;
            resourceInputs["serviceId"] = undefined /*out*/;
            resourceInputs["value"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const aliasOpts = { aliases: [{ type: "railway:pkg:Variable" }] };
        opts = pulumi.mergeOptions(opts, aliasOpts);
        const secretOpts = { additionalSecretOutputs: ["value"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        const replaceOnChanges = { replaceOnChanges: ["environmentId", "key", "projectId", "serviceId"] };
        opts = pulumi.mergeOptions(opts, replaceOnChanges);
        super(Variable.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Variable resource.
 */
export interface VariableArgs {
    /**
     * ID of the Railway environment that owns the variable.
     */
    environmentId: pulumi.Input<string>;
    /**
     * Variable name. It must be a valid environment variable identifier.
     */
    key: pulumi.Input<string>;
    /**
     * ID of the Railway project that owns the variable.
     */
    projectId: pulumi.Input<string>;
    /**
     * Optional service ID. Omit it for an environment-shared variable.
     */
    serviceId?: pulumi.Input<string | undefined>;
    /**
     * Secret variable value.
     */
    value: pulumi.Input<string>;
}
