// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * A persistent Railway volume attached to a service instance.
 */
export class Volume extends pulumi.CustomResource {
    /**
     * Get an existing Volume resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Volume {
        return new Volume(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'railway:index:Volume';

    /**
     * Returns true if the given object is an instance of Volume.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Volume {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Volume.__pulumiType;
    }

    /**
     * ID of the Railway environment where the volume is attached.
     */
    declare public readonly environmentId: pulumi.Output<string>;
    /**
     * Absolute mount path inside the service container.
     */
    declare public readonly mountPath: pulumi.Output<string>;
    /**
     * Optional display name for the volume.
     */
    declare public readonly name: pulumi.Output<string | undefined>;
    /**
     * ID of the Railway project that owns the volume.
     */
    declare public readonly projectId: pulumi.Output<string>;
    /**
     * Railway volume ID.
     */
    declare public /*out*/ readonly railwayId: pulumi.Output<string>;
    /**
     * ID of the Railway service where the volume is attached.
     */
    declare public readonly serviceId: pulumi.Output<string>;

    /**
     * Create a Volume resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: VolumeArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.environmentId === undefined && !opts.urn) {
                throw new Error("Missing required property 'environmentId'");
            }
            if (args?.mountPath === undefined && !opts.urn) {
                throw new Error("Missing required property 'mountPath'");
            }
            if (args?.projectId === undefined && !opts.urn) {
                throw new Error("Missing required property 'projectId'");
            }
            if (args?.serviceId === undefined && !opts.urn) {
                throw new Error("Missing required property 'serviceId'");
            }
            resourceInputs["environmentId"] = args?.environmentId;
            resourceInputs["mountPath"] = args?.mountPath;
            resourceInputs["name"] = args?.name;
            resourceInputs["projectId"] = args?.projectId;
            resourceInputs["serviceId"] = args?.serviceId;
            resourceInputs["railwayId"] = undefined /*out*/;
        } else {
            resourceInputs["environmentId"] = undefined /*out*/;
            resourceInputs["mountPath"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["projectId"] = undefined /*out*/;
            resourceInputs["railwayId"] = undefined /*out*/;
            resourceInputs["serviceId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const aliasOpts = { aliases: [{ type: "railway:pkg:Volume" }] };
        opts = pulumi.mergeOptions(opts, aliasOpts);
        const replaceOnChanges = { replaceOnChanges: ["environmentId", "projectId", "serviceId"] };
        opts = pulumi.mergeOptions(opts, replaceOnChanges);
        super(Volume.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Volume resource.
 */
export interface VolumeArgs {
    /**
     * ID of the Railway environment where the volume is attached.
     */
    environmentId: pulumi.Input<string>;
    /**
     * Absolute normalized mount path inside the service container.
     */
    mountPath: pulumi.Input<string>;
    /**
     * Optional display name for the volume.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * ID of the Railway project that owns the volume.
     */
    projectId: pulumi.Input<string>;
    /**
     * ID of the Railway service where the volume is attached.
     */
    serviceId: pulumi.Input<string>;
}
